/*
  # Corrective actions: link to source incident

  Adds an optional FK from safety_corrective_actions to the incident that
  triggered it, so a corrective action can be generated by selecting an
  incident. The existing free-text source_reference is retained for display.
*/

ALTER TABLE public.safety_corrective_actions
  ADD COLUMN IF NOT EXISTS source_incident_id uuid
    REFERENCES public.safety_incidents(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS safety_corrective_actions_source_incident_idx
  ON public.safety_corrective_actions (source_incident_id);
