/*
  # Seed Health & Safety Data

  Populates all six H&S tables with realistic sample data for a
  medical waste treatment facility covering Jan-May 2026.

  1. safety_incidents - 18 incidents (injuries, near misses, property damage, unsafe acts)
  2. safety_inspections - 20 inspections (site walks, PPE checks, fire safety, equipment)
  3. safety_risk_assessments - 12 risk assessments across various activities
  4. safety_corrective_actions - 15 corrective actions from incidents and inspections
  5. safety_toolbox_talks - 16 toolbox talks on various safety topics
  6. safety_emergency_drills - 8 emergency drills (fire, chemical spill, medical)
*/

-- ============================================================
-- INCIDENTS
-- ============================================================
INSERT INTO safety_incidents (incident_number, incident_date, incident_time, incident_type, severity, location, description, immediate_action, reported_by, injured_person, injury_type, body_part, witnesses, root_cause, status, closed_date) VALUES
('INC-2026-0001', '2026-01-08', '07:45', 'Near Miss', 'Minor', 'Loading Bay 2', 'Forklift nearly struck pedestrian worker who was crossing behind the vehicle without looking.', 'Area cordoned off. Driver and pedestrian both counselled on safety protocol.', 'J. Mokoena', '', '', '', 'S. Naidoo', 'Lack of designated pedestrian walkway markings in loading area.', 'Closed', '2026-01-15'),
('INC-2026-0002', '2026-01-14', '10:30', 'Injury', 'Moderate', 'Treatment Plant Floor', 'Operator sustained a cut to the right hand while handling broken sharps container.', 'First aid applied. Worker sent to clinic for stitches. Incident area cleaned.', 'M. Dlamini', 'T. Sibeko', 'Laceration', 'Right Hand', 'P. van Wyk, B. Khumalo', 'Damaged container not identified during receiving inspection.', 'Closed', '2026-01-28'),
('INC-2026-0003', '2026-01-22', '14:15', 'Unsafe Condition', 'Minor', 'Chemical Storage Room', 'Spill containment bund found cracked, allowing potential chemical seepage.', 'Area blocked off and maintenance called to assess repair.', 'R. Pillay', '', '', '', '', 'Ageing infrastructure. Bund not included in recent maintenance schedule.', 'Closed', '2026-02-05'),
('INC-2026-0004', '2026-02-03', '09:00', 'Property Damage', 'Minor', 'Parking Area', 'Delivery truck reversed into perimeter fence post causing minor damage.', 'Fence secured temporarily with cable ties. Repair scheduled.', 'A. Botha', '', '', '', 'D. Mthembu', 'Driver did not use spotter when reversing.', 'Closed', '2026-02-10'),
('INC-2026-0005', '2026-02-11', '11:20', 'Near Miss', 'Moderate', 'Autoclave Area', 'Steam release valve activated unexpectedly during maintenance. No injuries.', 'Maintenance halted. Equipment locked out and tagged out. Engineer consulted.', 'K. Govender', '', '', '', 'L. Nkosi, J. Mokoena', 'Lockout/tagout procedure not fully followed before maintenance began.', 'Closed', '2026-02-25'),
('INC-2026-0006', '2026-02-19', '06:30', 'Unsafe Act', 'Minor', 'Waste Receiving Bay', 'Worker observed sorting waste without wearing cut-resistant gloves.', 'Worker stopped immediately and issued correct PPE. Verbal warning issued.', 'S. Naidoo', '', '', '', '', 'Worker rushed to start shift, skipped PPE check.', 'Closed', '2026-02-20'),
('INC-2026-0007', '2026-03-05', '08:45', 'Injury', 'Minor', 'Admin Walkway', 'Employee slipped on wet floor near entrance. Bruised knee, no fracture.', 'First aid applied. Wet floor signs placed. Cleaning schedule reviewed.', 'P. van Wyk', 'N. Zulu', 'Bruise', 'Left Knee', 'A. Botha', 'No wet floor signage after early morning cleaning.', 'Closed', '2026-03-12'),
('INC-2026-0008', '2026-03-12', '13:00', 'Environmental', 'Moderate', 'Effluent Discharge Point', 'Elevated pH levels detected in effluent sample during routine testing.', 'Discharge halted. Sample sent to lab. Chemical dosing adjusted.', 'R. Pillay', '', '', '', '', 'Chemical dosing pump malfunction causing over-dosing of treatment chemicals.', 'Closed', '2026-03-20'),
('INC-2026-0009', '2026-03-18', '15:30', 'Near Miss', 'Minor', 'Loading Bay 1', 'Unsecured load shifted during transport within yard. No one in vicinity.', 'Load re-secured. Driver briefed on securing protocols.', 'D. Mthembu', '', '', '', 'T. Sibeko', 'Load straps were worn and not replaced during pre-trip inspection.', 'Closed', '2026-03-22'),
('INC-2026-0010', '2026-04-02', '10:00', 'Injury', 'Serious', 'Treatment Plant Floor', 'Operator experienced chemical splash to face when opening clogged treatment line.', 'Emergency eyewash used for 15 minutes. Transported to hospital immediately.', 'M. Dlamini', 'B. Khumalo', 'Chemical Burn', 'Face / Eyes', 'K. Govender, L. Nkosi', 'Blocked line built up pressure. SOP for clearing blockages not followed.', 'Corrective Action', null),
('INC-2026-0011', '2026-04-10', '07:15', 'Unsafe Condition', 'Minor', 'Emergency Exit B', 'Fire exit partially blocked by stored pallets.', 'Pallets removed immediately. Area cleared.', 'J. Mokoena', '', '', '', '', 'No assigned storage area for surplus pallets near treatment area.', 'Closed', '2026-04-11'),
('INC-2026-0012', '2026-04-17', '12:00', 'Near Miss', 'Minor', 'Truck Yard', 'Pedestrian gate left open allowing unauthorized vehicle access to pedestrian zone.', 'Gate closed and locked. Security informed.', 'A. Botha', '', '', '', 'S. Naidoo', 'Gate latch mechanism faulty. Security rounds missed this checkpoint.', 'Closed', '2026-04-20'),
('INC-2026-0013', '2026-04-25', '09:30', 'Unsafe Act', 'Moderate', 'Waste Sorting Area', 'Two workers not wearing face shields while handling pharmaceutical waste.', 'Workers stopped. PPE provided. Formal warning issued to both.', 'P. van Wyk', '', '', '', 'R. Pillay', 'Workers reported face shields were uncomfortable. Alternative shields to be sourced.', 'Corrective Action', null),
('INC-2026-0014', '2026-05-02', '14:45', 'Injury', 'Minor', 'Workshop', 'Maintenance worker pinched finger in equipment door. Minor swelling.', 'Ice applied. Worker returned to duties after rest.', 'K. Govender', 'D. Mthembu', 'Crush Injury', 'Right Index Finger', '', 'Equipment door spring tension too high.', 'Open', null),
('INC-2026-0015', '2026-05-08', '08:00', 'Environmental', 'Minor', 'Storm Water Drain', 'Oily sheen observed on storm water during heavy rain.', 'Oil absorbent booms deployed. Source traced to generator area.', 'R. Pillay', '', '', '', 'M. Dlamini', 'Generator drip tray overflow due to blocked drain hole.', 'Under Investigation', null),
('INC-2026-0016', '2026-05-15', '11:00', 'Near Miss', 'Moderate', 'Chemical Storage Room', 'Incompatible chemicals found stored on same shelf. Could have caused reaction.', 'Chemicals separated immediately. Storage audit initiated.', 'S. Naidoo', '', '', '', 'J. Mokoena, T. Sibeko', 'New stock placed by untrained temp worker.', 'Corrective Action', null),
('INC-2026-0017', '2026-05-22', '16:00', 'Property Damage', 'Minor', 'Treatment Plant Floor', 'Conveyor belt guard dislodged and fell, damaging sensor cable.', 'Equipment shut down. Maintenance called to repair guard and cable.', 'L. Nkosi', '', '', '', 'B. Khumalo', 'Guard mounting bolts had loosened over time. Not part of routine check.', 'Open', null),
('INC-2026-0018', '2026-05-28', '07:30', 'Unsafe Condition', 'Minor', 'Weighbridge Area', 'Weighbridge access ramp has uneven surface causing trip hazard.', 'Cones placed. Repair request submitted to facilities.', 'A. Botha', '', '', '', '', 'Surface erosion from heavy vehicle traffic.', 'Open', null);

-- ============================================================
-- INSPECTIONS
-- ============================================================
INSERT INTO safety_inspections (inspection_number, inspection_date, inspection_type, area, inspector, findings, items_checked, items_passed, score_percentage, status, next_inspection_date) VALUES
('INS-2026-0001', '2026-01-06', 'Site Walk', 'Full Site', 'J. Mokoena', 'Good general housekeeping. Minor issue with signage fading on chemical store door.', 25, 24, 96.00, 'Completed', '2026-02-03'),
('INS-2026-0002', '2026-01-13', 'PPE Check', 'Treatment Plant', 'S. Naidoo', 'All operators had correct PPE. 2 face shields scratched and need replacement.', 15, 13, 86.67, 'Requires Action', '2026-02-10'),
('INS-2026-0003', '2026-01-20', 'Fire Safety', 'Admin Building', 'R. Pillay', 'All extinguishers serviced. Emergency lighting functional. Exit B sign flickering.', 12, 11, 91.67, 'Completed', '2026-04-20'),
('INS-2026-0004', '2026-02-03', 'Site Walk', 'Full Site', 'J. Mokoena', 'Loading bay markings faded. Spill kit in chemical store needs replenishment.', 25, 22, 88.00, 'Requires Action', '2026-03-03'),
('INS-2026-0005', '2026-02-10', 'Equipment', 'Autoclave Room', 'K. Govender', 'Pressure gauges calibrated. Safety valve test passed. Door seal showing minor wear.', 10, 9, 90.00, 'Completed', '2026-05-10'),
('INS-2026-0006', '2026-02-17', 'Housekeeping', 'Waste Receiving Bay', 'P. van Wyk', 'Waste bins overflowing at shift change. Drainage grate blocked.', 20, 16, 80.00, 'Requires Action', '2026-03-17'),
('INS-2026-0007', '2026-03-03', 'Site Walk', 'Full Site', 'J. Mokoena', 'Improvement noted on loading bay. Chemical store signage replaced. Storm drain cover loose.', 25, 23, 92.00, 'Completed', '2026-04-07'),
('INS-2026-0008', '2026-03-10', 'Vehicle', 'Truck Fleet', 'D. Mthembu', 'Pre-trip checklists up to date. TF-003 brake lights intermittent. TF-005 tyre pressure low.', 18, 15, 83.33, 'Requires Action', '2026-04-10'),
('INS-2026-0009', '2026-03-17', 'PPE Check', 'All Departments', 'S. Naidoo', 'Replacement face shields issued. New cut-resistant gloves distributed. All compliant.', 20, 20, 100.00, 'Completed', '2026-04-14'),
('INS-2026-0010', '2026-03-24', 'Fire Safety', 'Treatment Plant', 'R. Pillay', 'Sprinkler heads clear. Hose reels accessible. Fire alarm panel showing fault on Zone 3.', 15, 13, 86.67, 'Requires Action', '2026-06-24'),
('INS-2026-0011', '2026-04-07', 'Site Walk', 'Full Site', 'J. Mokoena', 'Emergency exit B cleared. Generator area oily — needs cleaning. Good overall condition.', 25, 23, 92.00, 'Completed', '2026-05-05'),
('INS-2026-0012', '2026-04-14', 'Housekeeping', 'Admin & Offices', 'P. van Wyk', 'All areas clean. Filing room needs reorganisation. Kitchen area satisfactory.', 15, 14, 93.33, 'Completed', '2026-05-14'),
('INS-2026-0013', '2026-04-21', 'Equipment', 'Weighbridge', 'K. Govender', 'Calibration current. Ramp surface deteriorating (reported separately as incident).', 8, 7, 87.50, 'Requires Action', '2026-07-21'),
('INS-2026-0014', '2026-04-28', 'PPE Check', 'Treatment Plant', 'S. Naidoo', 'All PPE accounted for. Chemical aprons showing wear on 3 units. Ordered replacements.', 15, 12, 80.00, 'Requires Action', '2026-05-26'),
('INS-2026-0015', '2026-05-05', 'Site Walk', 'Full Site', 'J. Mokoena', 'Generator area cleaned. Storm drain repaired. Pedestrian gate latch replaced. Very good.', 25, 25, 100.00, 'Completed', '2026-06-02'),
('INS-2026-0016', '2026-05-12', 'Fire Safety', 'Warehouse / Storage', 'R. Pillay', 'Extinguishers current. Sprinklers tested OK. Exit signage needs replacement in Bay 3.', 12, 11, 91.67, 'Completed', '2026-08-12'),
('INS-2026-0017', '2026-05-14', 'Vehicle', 'Truck Fleet', 'D. Mthembu', 'TF-003 brake lights repaired. All vehicles compliant. TF-007 windscreen chip noted.', 18, 17, 94.44, 'Completed', '2026-06-14'),
('INS-2026-0018', '2026-05-19', 'Housekeeping', 'Treatment Plant', 'P. van Wyk', 'Shift change procedure improved. Bins managed well. Chemical spill kit fully stocked.', 20, 19, 95.00, 'Completed', '2026-06-19'),
('INS-2026-0019', '2026-05-26', 'PPE Check', 'All Departments', 'S. Naidoo', 'Replacement aprons received and issued. All PPE current and in good condition.', 20, 20, 100.00, 'Completed', '2026-06-23'),
('INS-2026-0020', '2026-05-30', 'Equipment', 'Autoclave Room', 'K. Govender', 'Scheduled inspection. Door seal replaced. All gauges within spec. Next service August.', 10, 10, 100.00, 'Completed', '2026-08-30');

-- ============================================================
-- RISK ASSESSMENTS
-- ============================================================
INSERT INTO safety_risk_assessments (assessment_number, assessment_date, area, activity, hazard, risk_description, likelihood, consequence, risk_rating, risk_level, existing_controls, additional_controls, responsible_person, review_date, status, assessed_by) VALUES
('RA-2026-0001', '2026-01-10', 'Treatment Plant', 'Autoclave Operation', 'High pressure steam', 'Operator exposure to steam burns if safety valve fails or door seal leaks.', 2, 4, 8, 'High', 'Safety valves tested quarterly. Operators trained. PPE required.', 'Install pressure relief alarm system. Quarterly door seal inspections.', 'K. Govender', '2026-07-10', 'Active', 'R. Pillay'),
('RA-2026-0002', '2026-01-10', 'Waste Receiving', 'Manual Sorting', 'Sharps injuries', 'Workers may sustain needlestick injuries from improperly packaged sharps.', 3, 4, 12, 'High', 'Cut-resistant gloves. Sharps training. Rejection of non-compliant loads.', 'Double-glove protocol for pharmaceutical waste. Automated sorting feasibility study.', 'S. Naidoo', '2026-07-10', 'Active', 'R. Pillay'),
('RA-2026-0003', '2026-01-15', 'Chemical Storage', 'Chemical Handling', 'Chemical exposure', 'Skin or respiratory exposure to treatment chemicals during decanting or mixing.', 2, 3, 6, 'Medium', 'MSDS available. Chemical aprons and goggles required. Ventilation system.', 'Upgrade ventilation extraction. Install automated dosing system.', 'R. Pillay', '2026-07-15', 'Active', 'R. Pillay'),
('RA-2026-0004', '2026-02-05', 'Loading Bays', 'Vehicle Movements', 'Pedestrian-vehicle collision', 'Pedestrians at risk of being struck by reversing trucks or forklifts.', 3, 4, 12, 'High', 'Speed limits. Reversing alarms. Spotters for trucks.', 'Paint dedicated pedestrian walkways. Install barrier bollards.', 'J. Mokoena', '2026-08-05', 'Active', 'J. Mokoena'),
('RA-2026-0005', '2026-02-12', 'Workshop', 'Equipment Maintenance', 'Mechanical injury', 'Workers may suffer crush or entanglement injuries during maintenance tasks.', 2, 3, 6, 'Medium', 'LOTO procedures. Trained personnel only. Tool inspections.', 'Review LOTO signage. Annual refresher training.', 'K. Govender', '2026-08-12', 'Active', 'K. Govender'),
('RA-2026-0006', '2026-03-01', 'Full Site', 'Fire Emergency', 'Fire and smoke', 'Workers at risk of burns, smoke inhalation, or being trapped during a fire.', 1, 5, 5, 'Medium', 'Fire detection system. Extinguishers. Evacuation plan. Quarterly drills.', 'Extend sprinkler coverage to new storage area. Update evacuation maps.', 'R. Pillay', '2026-09-01', 'Active', 'R. Pillay'),
('RA-2026-0007', '2026-03-15', 'Effluent Treatment', 'Effluent Discharge', 'Water pollution', 'Non-compliant discharge could cause environmental damage and regulatory fines.', 2, 4, 8, 'High', 'Daily pH and turbidity testing. Automated dosing. Discharge permits.', 'Install continuous online monitoring with auto-shutoff valve.', 'R. Pillay', '2026-09-15', 'Active', 'R. Pillay'),
('RA-2026-0008', '2026-03-20', 'Full Site', 'Working at Heights', 'Falls from height', 'Workers accessing roof or elevated platforms may fall.', 2, 5, 10, 'High', 'Harness required above 2m. Guardrails on platforms. Permit to work system.', 'Annual harness inspection register. Height rescue plan.', 'J. Mokoena', '2026-09-20', 'Active', 'J. Mokoena'),
('RA-2026-0009', '2026-04-01', 'Treatment Plant', 'Noise Exposure', 'Hearing damage', 'Prolonged exposure to noise from autoclave and shredder operations.', 3, 3, 9, 'High', 'Hearing protection provided. Noise zones marked. Audiometric testing annual.', 'Engineering noise reduction study on shredder. Rotate high-noise tasks.', 'K. Govender', '2026-10-01', 'Active', 'K. Govender'),
('RA-2026-0010', '2026-04-10', 'Truck Operations', 'Driving', 'Road traffic accident', 'Drivers transporting waste on public roads may be involved in collisions.', 2, 4, 8, 'High', 'Licenced drivers only. Pre-trip checks. Speed monitoring via GPS.', 'Defensive driving refresher course. Fatigue management policy.', 'D. Mthembu', '2026-10-10', 'Active', 'D. Mthembu'),
('RA-2026-0011', '2026-05-01', 'Admin Building', 'Office Work', 'Ergonomic strain', 'Prolonged sitting and screen use can cause musculoskeletal problems.', 3, 2, 6, 'Medium', 'Adjustable chairs provided. Screen break reminders.', 'Ergonomic assessment for all workstations. Standing desk trial.', 'P. van Wyk', '2026-11-01', 'Draft', 'P. van Wyk'),
('RA-2026-0012', '2026-05-15', 'Chemical Storage', 'Chemical Incompatibility', 'Chemical reaction', 'Incompatible chemicals stored together could cause fire, explosion, or toxic gas.', 2, 5, 10, 'High', 'Segregated storage by class. MSDS available. Trained personnel.', 'Colour-coded shelving. Only trained staff to receive chemical deliveries.', 'R. Pillay', '2026-11-15', 'Active', 'R. Pillay');

-- ============================================================
-- CORRECTIVE ACTIONS
-- ============================================================
INSERT INTO safety_corrective_actions (action_number, source_type, source_reference, description, assigned_to, priority, due_date, completed_date, evidence, status) VALUES
('CA-2026-0001', 'Incident', 'INC-2026-0001', 'Paint pedestrian walkway markings in loading bay areas.', 'J. Mokoena', 'High', '2026-02-15', '2026-02-12', 'Walkway lines painted. Photo evidence filed.', 'Verified'),
('CA-2026-0002', 'Incident', 'INC-2026-0002', 'Add sharps container inspection step to receiving checklist.', 'S. Naidoo', 'High', '2026-02-10', '2026-02-08', 'Updated checklist implemented. Training completed.', 'Verified'),
('CA-2026-0003', 'Incident', 'INC-2026-0003', 'Repair cracked spill containment bund in chemical storage.', 'K. Govender', 'High', '2026-02-28', '2026-02-20', 'Bund repaired by contractor. Integrity test passed.', 'Completed'),
('CA-2026-0004', 'Inspection', 'INS-2026-0002', 'Replace scratched face shields for treatment plant operators.', 'S. Naidoo', 'Medium', '2026-02-17', '2026-02-14', 'New shields issued to all affected operators.', 'Completed'),
('CA-2026-0005', 'Incident', 'INC-2026-0005', 'Retrain all maintenance staff on LOTO procedures.', 'K. Govender', 'Critical', '2026-03-15', '2026-03-10', 'Training session held 10 March. Attendance register filed.', 'Verified'),
('CA-2026-0006', 'Inspection', 'INS-2026-0004', 'Repaint loading bay floor markings and replenish chemical store spill kit.', 'J. Mokoena', 'Medium', '2026-03-20', '2026-03-18', 'Floor markings done. Spill kit restocked.', 'Completed'),
('CA-2026-0007', 'Inspection', 'INS-2026-0006', 'Implement shift-change waste bin management procedure.', 'P. van Wyk', 'Medium', '2026-04-01', '2026-03-28', 'Procedure documented and distributed. Bins managed at shift change.', 'Completed'),
('CA-2026-0008', 'Inspection', 'INS-2026-0008', 'Repair TF-003 brake lights and adjust TF-005 tyre pressure.', 'D. Mthembu', 'High', '2026-03-24', '2026-03-20', 'Both vehicles repaired and re-inspected.', 'Completed'),
('CA-2026-0009', 'Inspection', 'INS-2026-0010', 'Investigate and repair fire alarm panel Zone 3 fault.', 'R. Pillay', 'Critical', '2026-04-14', '2026-04-10', 'Faulty detector replaced. Panel tested clear.', 'Verified'),
('CA-2026-0010', 'Incident', 'INC-2026-0010', 'Develop SOP for clearing blocked treatment lines under pressure.', 'K. Govender', 'Critical', '2026-05-15', null, '', 'In Progress'),
('CA-2026-0011', 'Incident', 'INC-2026-0010', 'Install face-level chemical splash guards at treatment stations.', 'R. Pillay', 'Critical', '2026-05-30', null, '', 'In Progress'),
('CA-2026-0012', 'Incident', 'INC-2026-0013', 'Source comfortable alternative face shields for waste sorting.', 'S. Naidoo', 'High', '2026-05-20', '2026-05-18', 'New lightweight shields procured and distributed. Workers report improved comfort.', 'Completed'),
('CA-2026-0013', 'Incident', 'INC-2026-0016', 'Conduct full chemical storage audit and retrain temp workers on storage protocols.', 'R. Pillay', 'Critical', '2026-06-15', null, '', 'Open'),
('CA-2026-0014', 'Inspection', 'INS-2026-0013', 'Resurface weighbridge access ramp.', 'J. Mokoena', 'Medium', '2026-06-30', null, '', 'Open'),
('CA-2026-0015', 'Inspection', 'INS-2026-0014', 'Replace worn chemical aprons (3 units).', 'S. Naidoo', 'Medium', '2026-06-05', '2026-05-28', 'New aprons received and issued.', 'Completed');

-- ============================================================
-- TOOLBOX TALKS
-- ============================================================
INSERT INTO safety_toolbox_talks (talk_number, talk_date, topic, description, presented_by, duration_minutes, attendee_count, attendees, location, follow_up_required, follow_up_notes) VALUES
('TBT-2026-0001', '2026-01-07', 'New Year Safety Restart', 'Review of safety procedures after holiday shutdown. Emphasis on re-familiarisation with equipment and PPE requirements.', 'J. Mokoena', 20, 28, 'All operational staff', 'Canteen', false, ''),
('TBT-2026-0002', '2026-01-14', 'Sharps Handling Safety', 'Safe handling of sharps containers, recognition of damaged packaging, and injury response protocol.', 'S. Naidoo', 25, 15, 'Treatment plant operators, receiving bay staff', 'Treatment Plant', true, 'Follow up with practical demonstration for new employees.'),
('TBT-2026-0003', '2026-01-28', 'Forklift & Pedestrian Safety', 'Rules for pedestrians in vehicle movement areas. Spotter requirements. Right of way rules.', 'D. Mthembu', 20, 22, 'Drivers, warehouse staff, loading bay workers', 'Loading Bay 1', false, ''),
('TBT-2026-0004', '2026-02-11', 'Lockout/Tagout Refresher', 'LOTO procedures for maintenance work. Review of recent near miss. Practical examples.', 'K. Govender', 30, 12, 'Maintenance team, plant operators', 'Workshop', false, ''),
('TBT-2026-0005', '2026-02-25', 'Chemical Safety & MSDS', 'How to read MSDS. Chemical storage requirements. Emergency procedures for spills.', 'R. Pillay', 25, 18, 'All plant staff', 'Canteen', false, ''),
('TBT-2026-0006', '2026-03-04', 'Slip, Trip & Fall Prevention', 'Identifying slip and trip hazards. Importance of housekeeping. Wet floor protocols.', 'P. van Wyk', 15, 25, 'All staff', 'Canteen', false, ''),
('TBT-2026-0007', '2026-03-18', 'Defensive Driving', 'Safe driving practices for waste collection routes. Fatigue management. Pre-trip checks.', 'D. Mthembu', 25, 10, 'All drivers', 'Training Room', true, 'Schedule formal defensive driving course for Q2.'),
('TBT-2026-0008', '2026-04-01', 'Fire Safety Awareness', 'Types of fire extinguishers and their uses. Evacuation routes. Assembly points.', 'R. Pillay', 20, 30, 'All staff', 'Canteen', false, ''),
('TBT-2026-0009', '2026-04-08', 'PPE Care & Maintenance', 'Proper use, storage, and inspection of PPE. When to request replacements.', 'S. Naidoo', 20, 18, 'All operational staff', 'Treatment Plant', false, ''),
('TBT-2026-0010', '2026-04-22', 'Incident Reporting Culture', 'Importance of reporting all incidents including near misses. No-blame reporting.', 'J. Mokoena', 20, 28, 'All staff', 'Canteen', false, ''),
('TBT-2026-0011', '2026-05-06', 'Environmental Awareness', 'Effluent management, storm water protection, waste segregation, and spill response.', 'R. Pillay', 25, 22, 'Plant operators, drivers, yard staff', 'Canteen', false, ''),
('TBT-2026-0012', '2026-05-13', 'Noise & Hearing Protection', 'Noise exposure limits. Correct use of ear protection. Audiometric testing schedule.', 'K. Govender', 20, 14, 'Treatment plant operators, maintenance', 'Treatment Plant', false, ''),
('TBT-2026-0013', '2026-05-20', 'Chemical Incompatibility', 'Recognising incompatible chemicals. Storage rules. What to do if mis-stored.', 'R. Pillay', 25, 16, 'All plant staff, receiving staff', 'Chemical Storage', true, 'Implement colour-coded shelf labels by end of month.'),
('TBT-2026-0014', '2026-05-27', 'Heat Stress Awareness', 'Recognising signs of heat exhaustion. Hydration requirements. Rest schedules in summer.', 'S. Naidoo', 15, 24, 'All outdoor and plant workers', 'Canteen', false, ''),
('TBT-2026-0015', '2026-03-25', 'Working at Heights', 'Fall protection requirements. Harness inspection. Permit to work process.', 'J. Mokoena', 25, 8, 'Maintenance team, contractors', 'Workshop', false, ''),
('TBT-2026-0016', '2026-04-15', 'Manual Handling', 'Correct lifting techniques. When to use mechanical aids. Back injury prevention.', 'P. van Wyk', 20, 20, 'All operational staff', 'Canteen', false, '');

-- ============================================================
-- EMERGENCY DRILLS
-- ============================================================
INSERT INTO safety_emergency_drills (drill_number, drill_date, drill_type, location, coordinator, participants_count, evacuation_time_seconds, target_time_seconds, passed, observations, improvements, next_drill_date, status) VALUES
('DRL-2026-0001', '2026-01-15', 'Fire Evacuation', 'Full Site', 'R. Pillay', 32, 195, 180, false, 'Treatment plant staff took longer due to LOTO requirements before evacuation. Assembly point B had delayed roll call.', 'Pre-assign LOTO buddies for faster shutdown. Appoint additional assembly point marshals.', '2026-04-15', 'Completed'),
('DRL-2026-0002', '2026-02-12', 'Chemical Spill', 'Chemical Storage', 'R. Pillay', 8, 0, 0, true, 'Spill response team deployed containment within 4 minutes. Correct PPE donned. MSDS referenced appropriately.', 'Label spill kits more prominently. Add emergency contact card to each kit.', '2026-05-12', 'Completed'),
('DRL-2026-0003', '2026-03-05', 'Medical Emergency', 'Treatment Plant', 'S. Naidoo', 6, 0, 0, true, 'First aiders responded promptly. Correct use of emergency eyewash. Ambulance contact simulated successfully.', 'Update first aid kit inventory in treatment area. Add second eyewash station.', '2026-06-05', 'Completed'),
('DRL-2026-0004', '2026-04-15', 'Fire Evacuation', 'Full Site', 'R. Pillay', 35, 168, 180, true, 'Significant improvement. LOTO buddy system worked well. All personnel accounted for within target time.', 'Continue quarterly drills. Test night shift evacuation next.', '2026-07-15', 'Completed'),
('DRL-2026-0005', '2026-05-12', 'Chemical Spill', 'Treatment Plant', 'R. Pillay', 10, 0, 0, true, 'Spill in treatment area simulated. Team contained spill in 3 minutes. Ventilation activated correctly.', 'Practice with larger simulated spill next time. Include waste neutralisation step.', '2026-08-12', 'Completed'),
('DRL-2026-0006', '2026-05-20', 'Medical Emergency', 'Loading Bay', 'S. Naidoo', 5, 0, 0, true, 'Simulated crush injury. First aiders applied splint correctly. Communication to emergency services clear.', 'Add trauma first aid refresher to next training cycle.', '2026-08-20', 'Completed'),
('DRL-2026-0007', '2026-06-15', 'Fire Evacuation', 'Full Site', 'R. Pillay', 0, 0, 180, false, '', '', '2026-09-15', 'Scheduled'),
('DRL-2026-0008', '2026-07-10', 'Chemical Spill', 'Chemical Storage', 'R. Pillay', 0, 0, 0, false, '', '', '2026-10-10', 'Scheduled');
